.idea/.gitignore
.idea/go-mcp.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
client.go
examples/client.go
examples/server.go
go.mod
internal/client/client.go
internal/server/server.go
see_client.go
see_server.go
server.go
stdio_client.go
stdio_server.go

feat: init layout

---

.gitignore
protocol/types.go
server/handle.go
server/option.go
server/server.go
server/server_test.go

feat: server handlers simple implement

---

.github/workflows/lint.yml
.golangci.yml
Makefile
examples/current_time_server/main.go
examples/everything/main.go
transport/sse_client.go
transport/sse_server.go
transport/sse_test.go

fix: sse transport close

---

client/client_test.go
protocol/schema_generate.go
protocol/schema_validate.go
protocol/schema_validate_test.go
transport/mock_client.go

fix: mock client close

---

transport/sse_server.go
transport/sse_server_test.go

feat(sse/server): compatible with the official sse endpoint implementation

---

examples/http_handler/main.go

feat: add http_handler example

---

README.md
README_CN.md
examples/http_handler/main.go

feat: add update readme add Integration With Gin Server

---

client/client.go

fix: client hearbeat ctx

---

client/client.go
examples/current_time_server/main.go
examples/everything/main.go
examples/http_handler/main.go
server/server.go
server/session/manager.go
tests/utils.go

fix: hearbeat

---

server/receive.go

fix: server receiveResponse session check

---

protocol/prompts.go
protocol/resources.go
protocol/tools.go

New Audio Content In lastest MCP

feat: new audio content in MCP

---

transport/mock_client.go
transport/mock_server.go
transport/sse_server.go
transport/stdio_client.go
transport/stdio_server.go
transport/streamable_http_server.go

fix: stdio receive too long err

---

client/call.go
server/handle.go

fix: client version judge

---

protocol/schema_generate.go
protocol/schema_generate_test.go
protocol/schema_validate_test.go

feat(jsonschema): Add map support

---

.pre-commit-config.yaml
go.mod
go.sum
server/receive.go
transport/sse_client.go

feat: add sse client auto retry

---

server/handle.go
server/server.go
server/session/manager.go
transport/mock_server.go
transport/sse_server.go
transport/stdio_server.go
transport/streamable_http_client.go
transport/transport.go
transport/transport_test.go

feat: add genSessionID func

---

go.mod
go.sum
transport/sse_client.go

feat: sse client add retry option

---

client/call.go
examples/everything/main.go
protocol/types.go
server/call.go
server/handle.go
server/receive.go
server/session/state.go
transport/mock_server.go
transport/sse_server.go
transport/stdio_server.go
transport/streamable_http_server.go
transport/transport_test.go

feat: add cancelled

---

examples/everything/main.go
tests/utils.go

feat: optimization code

---

client/receive.go
examples/everything/main.go
tests/utils.go

feat: optimization progress notify handle

---

client/client.go
client/receive.go
protocol/jsonrpc.go
transport/mock_client.go
transport/sse_client.go
transport/stdio_client.go
transport/transport.go
transport/transport_test.go

feat: add receive interrupt

---

README.md
README_VI.md

This pull request translates the README.md documentation from English to Vietnamese to make the Go-MCP library more accessible to the Vietnamese developer community.

docs: add traditional Vietnamese support documentation on Readme

---

examples/auth_tool/main.go
examples/everything/main.go
transport/sse_server.go

feat: add auth tool

---

client/call.go
client/client.go
client/client_test.go
client/send.go
examples/everything/main.go
examples/filesystem_client/main.go
protocol/completion.go
protocol/initialize.go
protocol/pagination_test.go
protocol/prompts.go
protocol/resources.go
protocol/roots.go
protocol/sampling.go
server/handle.go
server/server_test.go
tests/utils.go

feat: optimization protocol struct

---

examples/middleware_example/main.go
server/server.go
server/server_test.go

fix: lint error

---

protocol/tools.go

tool outputSchema

---

server/session/state.go
transport/transport_test.go

feat: optimize ch close Judgement

---

transport/streamable_http_server.go

feat: streamable http server heartbeat add cancel
